<?php
$maxFileSize = \Magezon\AdvancedContact\Model\Contact::MAX_FILE_UPLOAD_SIZE;
$helper = $this->helper(Magezon\AdvancedContact\Helper\Data::class);
$iconLoading = $helper->getIconLoading();
$keyCaptcha = $helper->getSecurityCaptchaKey();
?>
<form class="form contact mz-contact-form"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      enctype="multipart/form-data"
      data-hasrequired="<?php echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field note no-label">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-notification')->toHtml() ?>
        </div>
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" 
                       id="name" 
                       title="<?= $block->escapeHtmlAttr(__('Name')) ?>" 
                       value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('name')) ?>" 
                       class="input-text validate-length maximum-length-80" 
                       type="text" 
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" 
                       id="email" 
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>" 
                       value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('email')) ?>" 
                       class="input-text validate-length maximum-length-255" 
                       type="email" 
                       data-validate="{required:true, 'validate-email-ext':true}"/>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment">
                <span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span>
            </label>
            <div class="control">
                <textarea name="comment" 
                     id="comment"
                     title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                     class="input-text validate-length maximum-length-2000"
                     cols="5"
                     rows="7"
                     data-validate="{required:true}"><?= $block->escapeHtml($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <div class="field attachment">
            <label class="label" for="attachment"><span><?= $block->escapeHtml(__('Attachment')) ?></span></label>
            <div class="control">
                <input type="file"
                       name="file_attach"
                       id="file-attach"
                       accept=".jpg,.jpeg,.gif,.png,.pdf"
                       data-validate="{'max-upload-size':true}"
                />
            </div>
            <div><?= $block->escapeHtml(__('Max file size: %1', '5 MB')); ?></div>
            <div><?= $block->escapeHtml(__('Allow file types: %1', 'jpg, jpeg, gif, png, pdf')); ?></div>
            <div class="attachment-description">
                <?= $block->getLayout()->createBlock(Magento\Cms\Block\Block::class)->setBlockId('attachment_description')->toHtml() ?>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
        <?php if ($block->getCaptchaStatus() == '1' && !empty($keyCaptcha)) { ?>
            <div class="g-recaptcha" data-sitekey="<?= $block->escapeHtml($keyCaptcha) ?>" data-callback="verifyCaptcha"></div>
            <div id="g-recaptcha-error"></div>
        <?php } ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" value="Submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                <span><?php echo __('Submit') ?></span>
            </button>
        </div>
    </div>
    <div class="btn-wrap">
        <a class="btn-back" href="<?= $block->getBaseUrl() ?>"><?= $block->escapeHtml(__('Back to product list')) ?></a>
    </div>
</form>
<div class="mz_loadfr">
	<div class="mz_loadfr_bg">
	</div>
  <?php if (!empty($iconLoading)) {  ?>
    <img class="loading" src="<?= $iconLoading ?>" alt="">
  <?php } else { ?>
    <section class="loading">
        <div class="circle"></div>
        <div class="circle"></div>
        <div class="circle"></div>
    </section>
  <?php } ?>
</div>
<script type="text/x-magento-init">
   {
       "*": {
           "maxUploadSizeMethod": {
                "maxSize": "<?= $maxFileSize ?>"
           }
       }
   }
</script>
